### ISSUE TITLE
TypeError: _configType.ends[key].reduce is not a function

### ISSUE THREAD

**Issue by wyze** [wyze/atom-flexicons#10]
Bug was introduced with 5eb1b711c0bef6a3ed928064cd43c39cafdf1da6.
